WbMiner\Entity\Image:
  type: mappedSuperclass
  repositoryClass: WbMiner\Image\DoctrineRepository

  id:
    originId:
      column: id
      type: integer

  fields:
    tags:
      type: json_array
      nullable: true

    purityLevel:
      column: purity_level
      type: integer

    fileName:
      column: file_name
      type: text
      nullable: true

    originUrl:
      column: origin_url
      type: string