WbMiner\Entity\Job:
  type: mappedSuperclass
  repositoryClass: WbMiner\Job\DoctrineRepository

  id:
    jobId:
      column: id
      type: integer
      generator:
        strategy: AUTO

  fields:
    originId:
      column: origin_id
      type: integer
      unique: true

    tags:
      type: json_array
      nullable: true

    purityLevel:
      column: purity_level
      type: integer

    originUrl:
      column: origin_url
      type: string

  lifecycleCallbacks:
    prePersist: [updateFields]
    preUpdate: [updateFields]